name       : intel-compute-runtime
version    : 21.30.20482
release    : 3
source     :
    - https://github.com/intel/compute-runtime/archive/refs/tags/21.30.20482.tar.gz : 978e8d8471e658beca650890ec0d3160a2aac958a3c865ce4b61d334c73b2fb1
license    : MIT
component  : programming.tools
homepage   : https://github.com/intel/compute-runtime/
summary    : Intel® Graphics Compute Runtime for oneAPI Level Zero and OpenCL™ Driver
description: |
    The Intel(R) Graphics Compute Runtime for oneAPI Level Zero and OpenCL(TM) Driver is an open source project providing compute API support (Level Zero, OpenCL) for Intel graphics hardware architectures (HD Graphics, Xe).
replaces   :
    - beignet
builddeps  :
    - pkgconfig(igdgmm)
    - pkgconfig(igc-opencl)
    - pkgconfig(libva)
    - pkgconfig(libze_loader)
libsplit   : no
setup      : |
    # revert the commit that causes the LLVM 12 new pass manager to fail
    %patch -p1 -R < $pkgfiles/ab52c702337358af57140e760d618549372e1cdd.patch

    # disable warnings as errors
    sed -i 's|-Werror||g' CMakeLists.txt
    %cmake_ninja \
        -DSKIP_UNIT_TESTS=ON \
        -DOCL_ICD_VENDORDIR=/usr/share/OpenCL/vendors
build      : |
    %ninja_build
install    : |
    %ninja_install
