name       : intel-compute-runtime
version    : 23.09.25812.14
release    : 9
source     :
    - https://github.com/intel/compute-runtime/archive/refs/tags/23.09.25812.14.tar.gz : abe2e6d9d2ac771d5f42ee2357ce897ca3b00dc6185c06f3f62772f729c7f8e1
license    : MIT
component  : programming.tools
homepage   : https://github.com/intel/compute-runtime/
summary    : Intel® Graphics Compute Runtime for oneAPI Level Zero and OpenCL™ Driver
description: |
    The Intel(R) Graphics Compute Runtime for oneAPI Level Zero and OpenCL(TM) Driver is an open source project providing compute API support (Level Zero, OpenCL) for Intel graphics hardware architectures (HD Graphics, Xe).
replaces   :
    - beignet
builddeps  :
    - pkgconfig(igdgmm)
    - pkgconfig(igc-opencl)
    - pkgconfig(libva)
    - pkgconfig(libze_loader)
    - pkgconfig(libdrm)
    - igsc-devel
    - git
rundeps    :
    - intel-graphics-compiler
libsplit   : no
clang      : yes
setup      : |
    # disable warnings as errors
    sed -i 's|-Werror -Werror=vla||g' CMakeLists.txt
    %cmake_ninja \
        -DSKIP_UNIT_TESTS=ON \
        -DSUPPORT_DG1=ON \
        -DOCL_ICD_VENDORDIR=/usr/share/OpenCL/vendors \
        -DNEO_SKIP_UNIT_TESTS=1 \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
